-- Add missing service operators from KwikAPI
-- This migration adds Water, Insurance, Broadband, and Landline operators that are missing from the database

-- Water operators
INSERT INTO kwikapi_billers (operator_id, operator_name, service_type, status, biller_status, bill_fetch, support_validation, bbps_enabled, message, description, amount_minimum, amount_maximum, is_active, created_at, updated_at) VALUES
(99, 'Uttarakhand Jal Sansthan', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(100, 'Urban Improvement Trust (UIT) - BHIWADI', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(101, 'Municipal Corporation of Gurugram', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(102, 'Delhi Jal Board', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(146, 'Ujjain Nagar Nigam - PHED', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(147, 'Surat Municipal Corporation', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(148, 'Pune Municipal Corporation', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(149, 'New Delhi Municipal Council (NDMC)', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(150, 'Municipal Corporation Ludhiana', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(151, 'Municipal Corporation Jalandhar', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(152, 'Jabalpur Municipal Corporation', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(154, 'Indore Municipal Corporation', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(155, 'Hyderabad Metropolitan Water Supply and Sewerage Board', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(156, 'Gwalior Municipal Corporation', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(157, 'Greater Warangal Municipal Corporation', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(158, 'Bhopal Municipal Corporation', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(159, 'Bangalore Water Supply and Sewerage Board', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(234, 'Haryana Urban Development Authority', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(235, 'Punjab Municipal Corporations/Councils', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(236, 'Kerala Water Authority (KWA)', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(237, 'Delhi Development Aunthority (DDA) - Water', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(238, 'Municipal Corporation Chandigarh', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(239, 'Silvassa Municipal Council', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(240, 'Jalkal Vibhag Nagar Nigam Prayagraj', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(241, 'Port Blair Municipal Council - Water', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(243, 'Municipal Corporation of Amritsar', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(244, 'Mysuru City Corporation', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(245, 'Department of Public Health Engineering-Water, Mizoram', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(246, 'Vasai Virar Municipal Corporation - Water', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(247, 'Madhya Pradesh Urban (e-Nagarpalika) - Water', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(248, 'Kalyan Dombivali Municipal Corporation', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(249, 'Ranchi Municipal Corporation', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(493, 'Municipal Corporation of Gurugram (MCG) - Water', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(494, 'Public Health Engineering Department, Haryana', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(495, 'Shimla Jal Prabandhan', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(496, 'Jammu Kashmir Water Billing-JKPHE Kashmir', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(497, 'Jammu Kashmir Water Billing-JKPHE Jammu', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(498, 'Nagar Nigam Aligarh', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(499, 'Vatva Industrial Estate Infrastructure Development Ltd', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(500, 'MCGM Water Department', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(502, 'Public Works Department (PWD),Goa', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(503, 'Jejuri Nagarparishad', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW()),
(504, 'Pimpri Chinchwad Municipal Corporation(PCMC)', 'Water', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 1, 49999, true, NOW(), NOW());

-- Insurance operators (active ones)
INSERT INTO kwikapi_billers (operator_id, operator_name, service_type, status, biller_status, bill_fetch, support_validation, bbps_enabled, message, description, amount_minimum, amount_maximum, is_active, created_at, updated_at) VALUES
(113, 'ICICI Prudential Life Insurance', 'Insurance', '1', 'off', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(197, 'Aegon Life Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(198, 'Reliance General Insurance Company LTD', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(199, 'Bajaj Allianz Life Insurance Company Limited', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(200, 'Max Bupa Health Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(201, 'Aviva Life Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(202, 'Bajaj Allianz General Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(203, 'Royal Sundaram General Insurance Co. Limited', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(204, 'Magma HDI - Life Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(205, 'Shriram General Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(206, 'Magma HDI - Health Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(207, 'Magma HDI - Motor Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(447, 'Canara HSBC Life Insurance Ltd', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(448, 'The Oriental Insurance Company Limited', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(449, 'Care Health Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(450, 'Iffco Tokio General Insurance Company Limited', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(451, 'Pramerica Life Insurance Limited', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(452, 'Max Life Insurance Company Limited', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(453, 'Shriram General Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(454, 'Shriram General Insurance - Quote Payment', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(456, 'HDFC Life Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(457, 'Aditya Birla Health Insurance Co Limited', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(458, 'Ageas Federal Life Insurance Company Limited', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(459, 'TATA AIA Life Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(460, 'Aditya Birla Sun Life Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(462, 'Future Generali India Life Insurance Company Limited', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(463, 'HDFC ERGO General Insurance (Motor)', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(464, 'ICICI Lombard General Insurance (Motor)', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(465, 'ICICI Lombard General Insurance (Health)', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(467, 'ICICI Prudential Life Insurance - New', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(468, 'BHARTI AXA Life Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(469, 'Kotak Life Insurance Company Limited', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(470, 'Reliance General Insurance Company Limited (Health)', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(471, 'Reliance Nippon Life Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(472, 'IndiaFirst Life Insurance Company Ltd', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(473, 'ManipalCigna Health Insurance', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(474, 'SBI Life Insurance Company Limited', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW()),
(475, 'Edelweiss Tokio Life Insurance Company Limited', 'Insurance', '1', 'on', 'NO', 'NOT_SUPPORTED', 'NO', 'NA', '', 100, 100000, true, NOW(), NOW());

-- Broadband operators (active ones)
INSERT INTO kwikapi_billers (operator_id, operator_name, service_type, status, biller_status, bill_fetch, support_validation, bbps_enabled, message, description, amount_minimum, amount_maximum, is_active, created_at, updated_at) VALUES
(108, 'Tikona Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(109, 'Connect Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(136, 'Hathway Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(137, 'ACT Fibernet', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(166, 'TTN BroadBand', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(167, 'Spectranet Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(168, 'Airtel Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(169, 'Nextra Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(250, 'Vfibernet Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(251, 'Fusionnet Web Services Private Limited', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(252, 'Excell Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(253, 'Netplus Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(254, 'Mnet Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(255, 'Timbl Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(256, 'Instalinks', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(257, 'ION', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(258, 'Swifttele Enterprises Private Limited', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(259, 'DEN Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(260, 'Comway Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(261, 'Flash Fibernet', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(262, 'Instanet Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(263, 'Asianet Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(309, 'B Fibernet', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(310, 'Manas Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(311, 'Aitspl', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(312, 'Softnet Digital', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(313, 'Baroda Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(314, 'Quest Consultancy Pvt Ltd', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(315, 'Arihant Network', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(316, 'Net 9 Fibernet Private Limited', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(317, 'NS Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(318, 'Airnet Networks', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(319, 'One Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(320, 'Auriga', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(321, 'Microscan  Infocommtech Pvt. Ltd.', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(322, 'Wizbyte Networks Pvt Ltd', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(323, 'GBPS Networks Pvt Ltd', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(324, 'Netway Infotech Private Limited', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(325, 'Super Sonic Broadband Private Limited', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(326, 'Ssky Conneect Private Limited', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(327, 'Infinet', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(328, 'Ethernet Xpress', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(329, 'SCCNET', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(330, 'Imperium Digital Network Private Limited', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(331, 'Skynet Fiber Broadband', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW()),
(333, 'Skynet Internet Broadband Pvt Ltd', 'Broadband', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 100, 50000, true, NOW(), NOW());

-- Landline operators (active ones)
INSERT INTO kwikapi_billers (operator_id, operator_name, service_type, status, biller_status, bill_fetch, support_validation, bbps_enabled, message, description, amount_minimum, amount_maximum, is_active, created_at, updated_at) VALUES
(103, 'Tata Docomo CDMA (LL)', 'Landline', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 10, 50000, true, NOW(), NOW()),
(104, 'MTNL - Mumbai(LL)', 'Landline', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 10, 50000, true, NOW(), NOW()),
(105, 'MTNL - Delhi(LL)', 'Landline', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 10, 50000, true, NOW(), NOW()),
(107, 'Airtel(LL)', 'Landline', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 10, 50000, true, NOW(), NOW()),
(273, 'BSNL Individual New(LL)', 'Landline', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 10, 50000, true, NOW(), NOW()),
(274, 'BSNL Landline - Corporate New(LL)', 'Landline', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 10, 50000, true, NOW(), NOW()),
(491, 'Airtel Landline', 'Landline', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 10, 50000, true, NOW(), NOW()),
(492, 'MTNL Mumbai (Multiple Bills)', 'Landline', '1', 'on', 'YES', 'NOT_SUPPORTED', 'YES', 'NA', '', 10, 50000, true, NOW(), NOW());

-- Handle conflicts by updating existing records if they exist
-- This is a safer approach than using ON CONFLICT which might not be supported in all databases